version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pessoas
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1